#!/bin/bash

ifcfg=wlx503eaa629e74
while true; do
    rfkill unblock all
    killall wpa_supplicant
    killall dhclient
    /sbin/wpa_supplicant -B -u -s -c /etc/wpa_supplicant.conf -D wext -i ${ifcfg}
    sleep 5
    dhclient -nw -v ${ifcfg}

    sleep 30
    while ping -c 1 www.google.com; do sleep 10; done
done
